### ISSUE TITLE
Could not find module `fetch` imported from `ember-cli-fastboot-testing/test-support/index`

### ISSUE THREAD

**Issue by chrism** [embermap/ember-cli-fastboot-testing#15]
Hi,

After installing the addon with
`ember install ember-cli-fastboot-testing`

and generating a test with
`ember g fastboot-test fingerprinted-path`

I get this error when trying to run the tests with
`ember test --server`

```
TestLoader Failures: dummy/tests/fastboot/fingerprinted-path-test: could not be loaded (1, 0, 1)


Error: Could not find module `fetch` imported from `ember-cli-fastboot-testing/test-support/index`
  at missingModule (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:252:11)
  at findModule (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:263:7)
  at Module.findDeps (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:173:24)
  at findModule (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:267:11)
  at Module.findDeps (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:173:24)
  at findModule (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:267:11)
  at requireModule (http://localhost:7357/assets/vendor-098320b95328ca4de617a0498ced5e00.js:29:15)
  at TestLoader.require (http://localhost:7357/assets/tests-17afb8ac72971fb2872e0fe3db40269c.js:2803:9)
  at TestLoader.loadModules (http://localhost:7357/assets/tests-17afb8ac72971fb2872e0fe3db40269c.js:2796:14)
  at loadTests (http://localhost:7357/assets/tests-17afb8ac72971fb2872e0fe3db40269c.js:3440:22)
```

I'm using the addon to test an addon I'm working on.

Thanks!

**Comment by ryanto** [comment]
Thanks for the fix! Published as `0.0.7`
