### ISSUE TITLE
upgrading from 0.0.13 to 0.0.14 breaks tests

### ISSUE THREAD

**Issue by 0xadada** [embermap/ember-cli-fastboot-testing#44]
My app uses `ember-fetch`, so my `package.json` declares:
https://github.com/mirai-audio/mir/blob/4468041c729b3fc30cdfed8bd2f52ac6406f2a1e/package.json#L95-L97

```json
...
"fastbootDependencies": [
    "node-fetch"
  ]
```

my test is pretty basic:
https://github.com/mirai-audio/mir/blob/master/tests/fastboot/welcome-route-test.js
```javascript
import { module, test } from 'qunit';
import { setup, visit } from 'ember-cli-fastboot-testing/test-support';

module('FastBoot | welcome route test', function(hooks) {
  setup(hooks);

  test('it renders the /welcome route', async function(assert) {
    let { htmlDocument } = await visit('/welcome');
    assert.dom('title', htmlDocument).hasText('mirai.audio');
    assert.dom('div').includesText('Play everything, play everywhere');
  });
});
```
currently passes on `0.0.13`, but going to `0.0.14` breaks the test.

```bash
... 
There was an error running your app in fastboot. More info about the error:
 Error: Assertion Failed: You attempted to define a `{{link-to "application"}}` but did not pass the parameters required for generating its dynamic segments. Cannot find module 'abortcontroller-polyfill/dist/cjs-ponyfill' from '/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets'
    at new EmberError (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@ember/error/index.js:37:1)
    at assert (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@ember/debug/index.js:125:1)
    at Class.computeLinkToComponentHref (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:1972:1)
    at ComputedProperty.get (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-metal.js:2515:1)
    at _get (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-metal.js:1356:1)
    at RootPropertyReference.compute (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:346:1)
    at RootPropertyReference.value (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:223:1)
    at ComponentElementOperations.flush (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:1327:1)
    at Object.evaluate (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:860:1)
    at AppendOpcodes.evaluate (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:46:1)
    at LowLevelVM.evaluateSyscall (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:2895:1)
    at LowLevelVM.evaluateInner (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:2867:1)
    at LowLevelVM.evaluateOuter (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:2859:1)
    at VM.next (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:4787:1)
    at TemplateIteratorImpl.next (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/@glimmer/runtime.js:4879:1)
    at RootState.render (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4070:1)
    at TransactionRunner.runInTransaction (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-metal.js:406:1)
    at InertRenderer._renderRoots (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4340:1)
    at InertRenderer._renderRootsTransaction (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4372:1)
    at InertRenderer._revalidate (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4412:1)
    at invokeWithOnError (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:283:1)
    at Queue.flush (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:186:1)
    at DeferredActionQueues.flush (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:353:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:808:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner.end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:558:1)
    at Backburner._run (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:847:1)
    at Backburner._join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:829:1)
    at Backburner.join (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:612:1)
    at Array.loopEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/ember-glimmer.js:4185:1)
    at Backburner._trigger (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:901:1)
    at Backburner._end (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:820:1)
    at Backburner._boundAutorunEnd (/var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-635989Jkue2teQwtI/out-402-srihash_assets/assets/backburner.js:528:1)
(node:63598) UnhandledPromiseRejectionWarning: Error: infinite rendering invalidation detected
(node:63598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:63598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
not ok 25 Chrome 73.0 - [379 ms] - FastBoot | welcome route test: it renders the /welcome route
    ---
        actual: >

        expected: >
            mirai.audio
        stack: >
                at DOMAssertions.hasText (http://localhost:7357/assets/test-support.js:9861:20)
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:371:41)
        message: >
            Element title has text "mirai.audio"
        negative: >
            false
        Log: |
    ...
```

## Details:

yarn produces the following relevant versions:
```bash
$ grep '"version"' -B 1 node_modules/*fastboot*/package.json
node_modules/ember-cli-fastboot-testing/package.json-  "name": "ember-cli-fastboot-testing",
node_modules/ember-cli-fastboot-testing/package.json:  "version": "0.0.13",
--
node_modules/ember-cli-fastboot/package.json-  "name": "ember-cli-fastboot",
node_modules/ember-cli-fastboot/package.json:  "version": "2.0.4",
--
node_modules/fastboot-express-middleware/package.json-  "name": "fastboot-express-middleware",
node_modules/fastboot-express-middleware/package.json:  "version": "1.2.0",
--
node_modules/fastboot-transform/package.json-  "name": "fastboot-transform",
node_modules/fastboot-transform/package.json:  "version": "0.1.3",
--
node_modules/fastboot/package.json-  "name": "fastboot",
node_modules/fastboot/package.json:  "version": "1.2.1",
```

```bash
$ ember --version --verbose
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: mir -> ember-test-component -> ember-cli-babel
ember-cli: 3.9.0
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
```

## Reproduce
The repo is currently using this addon v0.0.13, so all you'd have to do to reproduce is just upgrade to `0.0.14` and run `ember test --filter "FastBoot | Welcome"`

```bash
git clone git@github.com:mirai-audio/mir.git
ember test --filter "FastBoot | Welcome" # should pass test
yarn test --filter "FastBoot | Welcome" # should pass test
# upgrade to 0.0.14
ember test --filter "FastBoot | Welcome" # should pass test
yarn test --filter "FastBoot | Welcome" # should FAIL test
```

**Comment by CvX** [comment]
0.0.11 updated fastboot dependency to 2.x. There's currently an incompatibility issue with fastboot 2.x and ember-fetch. See: https://github.com/ember-cli/ember-fetch/issues/184 and https://github.com/ember-fastboot/ember-cli-fastboot/issues/686

A best workaround for now is to lock fastboot to 1.x, by adding this to your package.json:

```json
  "resolutions": {
    "fastboot": "^1.2.1"
  }
```

**Comment by ryanto** [comment]
Oh wow, in `0.0.11` I wanted to add compatibility with FastBoot 2.0, not force an upgrade. Yikes!

Let me make a new release that sets the FastBoot version back to `^1.2.1`

**Comment by 0xadada** [comment]
Actually, I tried upgrading first `0.0.11` and then `0.0.13`, it was jumping from `0.0.13` to `0.0.14` where it blew up.

**Comment by ryanto** [comment]
Ok, so just to confirm `0.0.11` and `0.0.13` work in your app? It's `0.0.14` that errors?

**Comment by CvX** [comment]
fwiw in my app it was the 0.0.11 and the update to fastboot 2.x. That resulted in "abortcontroller-polyfill/dist/cjs-ponyfill" error on build time.

@0xadada case might be different, since it seems that's a runtime error (with a failed assertion and an infinite rendering)

**Comment by ryanto** [comment]
Thanks @CvX  - You used yarn resolutions to fix it?

**Comment by CvX** [comment]
> You used yarn resolutions to fix it?

That's right. I'm currently using ember-cli-fastboot-testing 0.0.14 and fastboot locked via resolutions to "^1.2.1".

**Comment by 0xadada** [comment]
> Ok, so just to confirm `0.0.11` and `0.0.13` work in your app? It's `0.0.14` that errors? @ryanto 

Yup, going from `0.0.13` to `0.0.14` is where i'm seeing the failures. I was able to get `0.0.13` working after doing a completely new `yarn` install. I'll edit the OP to clarify.

**Comment by 0xadada** [comment]
@ryanto @CvX the package versions output by `yarn` for this repo:

```bash
$ grep '"version"' -B 1 node_modules/*fastboot*/package.json
node_modules/ember-cli-fastboot-testing/package.json-  "name": "ember-cli-fastboot-testing",
node_modules/ember-cli-fastboot-testing/package.json:  "version": "0.0.13",
--
node_modules/ember-cli-fastboot/package.json-  "name": "ember-cli-fastboot",
node_modules/ember-cli-fastboot/package.json:  "version": "2.0.4",
--
node_modules/fastboot-express-middleware/package.json-  "name": "fastboot-express-middleware",
node_modules/fastboot-express-middleware/package.json:  "version": "1.2.0",
--
node_modules/fastboot-transform/package.json-  "name": "fastboot-transform",
node_modules/fastboot-transform/package.json:  "version": "0.1.3",
--
node_modules/fastboot/package.json-  "name": "fastboot",
node_modules/fastboot/package.json:  "version": "1.2.1",
```

**Comment by ryanto** [comment]
Ok great. Thanks for the detailed info!

I added some new features related to network requests in 0.0.14 that probably need some better tests. 

I'll get that fixed, but for now use `0.0.13` since that appears to be working

**Comment by 0xadada** [comment]
@ryanto if you point me in the right direction, i could potentially add some tests later this week.

**Comment by 0xadada** [comment]
@ryanto oh whoa, i found something even more interesting: If i run `ember test` it passes, but If i enable code coverage, it fails with a different error related to networking. 

version `0.0.13`
```bash
$ ember test --filter "FastBoot | Welcome" # PASSes test
$ COVERAGE=true ember test --filter "FastBoot | Welcome" # PASSes test
```

version `0.0.14`
```bash
$ ember test --filter "FastBoot | Welcome" # PASSes test
$ COVERAGE=true ember test --filter "FastBoot | Welcome" # FAIL test
```

the error is as follows:
```
not ok 202 Chrome 74.0 - [undefined ms] - Global error: Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json'). at http://localhost:7357/228108987734153/tests/index.html?hidepassed, line 96
 After execution of test: ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
    ---
        Log: |
            { type: 'error',
              testContext:
               { id: 201,
                 name:
                  'ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly',
                 items: [],
                 state: 'complete' },
              text:
               'Uncaught InvalidStateError: Failed to read the \'responseText\' property from \'XMLHttpRequest\': The value is only accessible if the object\'s \'responseType\' is \'\' or \'text\' (was \'json\'). at http://localhost:7357/228108987734153/tests/index.html?hidepassed, line 96\n' }
    ...
```

I have a strong feeling that when [ember-cli-code-coverage](https://github.com/kategengler/ember-cli-code-coverage/) sends the coverage report back, it uses an AJAX request that has been modified to interact with fastboot.

**Comment by ryanto** [comment]
Thanks @0xadada 

Did this addon work in 0.0.13 with `COVERAGE=true`?

**Comment by 0xadada** [comment]
@ryanto yup, heres the breakdown

version `0.0.13`
```bash
$ ember test --filter "FastBoot | Welcome" # PASSes test
$ COVERAGE=true ember test --filter "FastBoot | Welcome" # PASSes test
```

version `0.0.14`
```bash
$ ember test --filter "FastBoot | Welcome" # PASSes test
$ COVERAGE=true ember test --filter "FastBoot | Welcome" # FAIL test

**Comment by ryanto** [comment]
Thanks! I just noticed you already answered that question above!!!

I think I *might* have figured it out, can you do me a favor and try out branch? https://github.com/embermap/ember-cli-fastboot-testing/pull/46

**Comment by 0xadada** [comment]
@ryanto yup, that worked 👌 🎉

**Comment by ryanto** [comment]
Woooohoooooo!!!!!

I'll cut a release once CI passes

**Comment by 0xadada** [comment]
@ryanto out of curiosity, how do you start the app and step your debugger through this? some magickal incantation of `node --inspect-brk ./node_modules/.bin/ember serve` or some such, and then attach chrome inspector?

**Comment by ryanto** [comment]
@0xadada Yup, I made a video about this exact sort of thing! https://embermap.com/video/faster-node-debugging

**Comment by ryanto** [comment]
Alright this is fixed and released in `0.0.15`

**Comment by ryanto** [comment]
Btw, thanks for doing all the debugging on this one @0xadada

**Comment by runspired** [comment]
I'm hitting this with the following:

```
ember-cli-fastboot 3.3.2
├── fastboot 3.3.2
└─┬ fastboot-express-middleware 3.3.2
  └── fastboot 3.3.2
ember-cli-fastboot-testing 0.6.0
└── fastboot 3.3.2
 ```

**Comment by runspired** [comment]
I believe the issue here is an undeclared dependency on `abortcontroller-polyfill`

**Comment by ryanto** [comment]
Thanks runspired. What's the fix? Should we have `abortcontroller-polyfill` as a dep of this library?

**Comment by runspired** [comment]
@ryanto I think it needs be a dep but I forget if this library for ember-fetch was the culprit, I ended up ripping out ember-fetch and we're still testing with this library in ember-data so I'm guessing it was ember-fetch.
