### ISSUE TITLE
Deploy is broken

### ISSUE THREAD

**Issue by ryanto** [embermap/ember-cli-fastboot-testing#58]
Looks like the deploy stage is erroring.

**Comment by CvX** [comment]
Updating in-range dependencies (https://github.com/embermap/ember-cli-fastboot-testing/commit/422c0bc1acfd7962b1ae164f1d82fb0c9833130c) does fix the production build for me, but now I can't get the development/test build to complete (with or without those updates 😬).

**Comment by ryanto** [comment]
Looks related to this one maybe: https://github.com/ember-learn/ember-cli-addon-docs/pull/259

I'll PR, hopefully that'll fix your dev env

**Comment by ryanto** [comment]
> Updating in-range dependencies (422c0bc) does fix the production build for me, but now I can't get the development/test build to complete (with or without those updates 😬).

The joys of nodejs development :D

**Comment by CvX** [comment]
Hm… #59 did fix the production build, but I still have the development/test issue.

It works on node 12, but when I switched to node 6 (to match the travis environment), it fails because the JS output in dev/test contains async/await stuff, which isn't supported by that node version. The production build is ok because that stuff is probably transformed to use promises instead.

I don't get it why it doesn't break on CI… 🤔 Could you confirm whether or not it works for you (locally, on node 6)?

Btw. here are the error details:

```
  - stack: /Users/cvx/dev/ember-cli-fastboot-testing/tmp/broccoli_merge_trees-output_path-8szewS9x.tmp/assets/vendor.js:167455
    async methodForRequest({ method = HTTP_METHOD_GET }) {
          ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at VMSandbox.eval (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/ember-app.js:156:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/ember-app.js:153:21)
    at EmberApp.retrieveSandboxedApp (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/fastboot/src/index.js:52:10)
    at Class.postBuild (/Users/cvx/dev/ember-cli-fastboot-testing/index.js:137:23)
    at addonPromises.project.addons.reduce (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/ember-cli/lib/models/builder.js:133:28)
    at Array.reduce (native)
    at Builder.processAddonBuildSteps (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/ember-cli/lib/models/builder.js:130:43)
    at tryCatcher (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at publish (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:197:7)
    at flush (/Users/cvx/dev/ember-cli-fastboot-testing/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by ryanto** [comment]
Oh, it might be because CI has env `CI=true` which changes Ember's targets/build output. (We just ran into this with mirage)

Also, I'm all for dropping node 6 at this point. Might as well support 8+

**Comment by CvX** [comment]
> Oh, it might be because CI has env `CI=true` which changes Ember's targets/build output. (We just ran into this with mirage)

Yeah, that's probably it. Super confusing! 😄

> Also, I'm all for dropping node 6 at this point. Might as well support 8+

👍 🙂

**Comment by CvX** [comment]
Btw. the build of `master` branch passed (incl. the `deploy` stage). I think we can close this issue. 🙂

**Comment by ryanto** [comment]
👍
